import { colorTokens } from '../tokens';
import { DeprecatedColorTokens } from '../tokens';

export const colorPrimitives = {
  '--color-brand-red': colorTokens.brandRed,
  '--color-brand-green': colorTokens.brandGreen,
  '--color-brand-yellow': colorTokens.brandYellow,
  '--color-brand-fur': colorTokens.brandFur,
  '--color-brand-nose': colorTokens.brandNose,
  '--color-brand-blue': colorTokens.brandBlue,
  '--color-brand-dark-blue': colorTokens.brandDarkBlue,
  '--color-darker-blue50': colorTokens.darkerBlue50,
  '--color-darker-blue10': colorTokens.darkerBlue10,
  '--color-blue10': colorTokens.blue10,
  '--color-blue20': colorTokens.blue20,
  '--color-blue40': colorTokens.blue40,
  '--color-blue50': colorTokens.blue50,
  '--color-blue60': colorTokens.blue60,
  '--color-blue80': colorTokens.blue80,
  '--color-white-on-dark-blue5': colorTokens.whiteOnDarkBlue5,
  '--color-white-on-dark-blue10': colorTokens.whiteOnDarkBlue10,
  '--color-white-on-dark-blue20': colorTokens.whiteOnDarkBlue20,
  '--color-white-on-dark-blue40': colorTokens.whiteOnDarkBlue40,
  '--color-white-on-dark-blue50': colorTokens.whiteOnDarkBlue50,
  '--color-white-on-dark-blue60': colorTokens.whiteOnDarkBlue60,
  '--color-white-on-dark-blue80': colorTokens.whiteOnDarkBlue80,
  '--color-white-on-blue5': colorTokens.whiteOnBlue5,
  '--color-white-on-blue10': colorTokens.whiteOnBlue10,
  '--color-white-on-blue20': colorTokens.whiteOnBlue20,
  '--color-white-on-blue40': colorTokens.whiteOnBlue40,
  '--color-white-on-blue50': colorTokens.whiteOnBlue50,
  '--color-white-on-blue60': colorTokens.whiteOnBlue60,
  '--color-white-on-blue80': colorTokens.whiteOnBlue80,
  '--color-white100': colorTokens.white100,
  '--color-white80': colorTokens.white80,
  '--color-white60': colorTokens.white60,
  '--color-white40': colorTokens.white40,
  '--color-white20': colorTokens.white20,
  '--color-black': colorTokens.black,
  '--color-black50': colorTokens.black50,
  '--color-green-alpha': colorTokens.greenAlpha,
  '--color-green80': colorTokens.green80,
  '--color-green40': colorTokens.green40,
  '--color-red-alpha': colorTokens.redAlpha,
  '--color-red80': colorTokens.red80,
  '--color-red40': colorTokens.red40,
  '--color-darker-blue10-alpha80': colorTokens.darkerBlue10Alpha80,
  '--color-darker-blue10-alpha40': colorTokens.darkerBlue10Alpha40,
  '--color-darker-blue50-alpha80': colorTokens.darkerBlue50Alpha80,
};

export const colors = {
  field: {
    onBackground: 'var(--color-white-on-dark-blue10)',
    onBackgroundFocused: 'var(--color-white100)',
    onBackgroundDisabled: 'var(--color-white-on-dark-blue50)',
    onBackgroundHover: 'var(--color-white-on-dark-blue40)',
    onPrimary: 'var(--color-white-on-blue10)',
    onPrimaryFocused: 'var(--color-white100)',
    onPrimaryDisabled: 'var(--color-white-on-blue5)',
    onPrimaryHover: 'var(--color-white-on-blue20)',
  },
  icon: {
    primary: 'var(--color-white100)',
    primaryHover: 'var(--color-white60)',
    secondary: 'var(--color-white60)',
    secondaryHover: 'var(--color-white100)',
    disabled: 'var(--color-white20)',
    fieldPrimary: 'var(--color-white-on-dark-blue60)',
    positive: 'var(--color-brand-green)',
    positiveDisabled: 'var(--color-green-alpha)',
    negative: 'var(--color-brand-red)',
    negativeDisabled: 'var(--color-red-alpha)',
    warning: 'var(--color-brand-yellow)',
  },
  brand: {
    red: 'var(--color-brand-red)',
    green: 'var(--color-brand-green)',
    yellow: 'var(--color-brand-yellow)',
    blue: 'var(--color-brand-blue)',
    darkBlue: 'var(--color-brand-dark-blue)',
    fur: 'var(--color-brand-fur)',
    nose: 'var(--color-brand-nose)',
    helmet: 'var(--color-brand-yellow)',
    lampAndText: 'var(--color-white100)',
  },
  overlay: {
    solid: 'var(--color-darker-blue50)',
    solid80: 'var(--color-darker-blue50-alpha80)',
    solidDark: 'var(--color-darker-blue10)',
    solidDark80: 'var(--color-darker-blue10-alpha80)',
    solidDark40: 'var(--color-darker-blue10-alpha40)',
  },
  surface: {
    white: 'var(--color-white100)',
    primary: 'var(--color-brand-blue)',
    primaryHighlight: 'var(--color-white-on-blue5)',
    primaryPressed: 'var(--color-white-on-blue10)',
    primaryDisabled: 'var(--color-blue40)',
    secondary: 'var(--color-blue60)',
    tertiary: 'var(--color-blue40)',
    quaternary: 'var(--color-blue20)',
    quinary: 'var(--color-blue10)',
    positive: 'var(--color-brand-green)',
    positiveHighlight: 'var(--color-green80)',
    positiveDisabled: 'var(--color-green40)',
    negative: 'var(--color-brand-red)',
    negativeHighlight: 'var(--color-red80)',
    negativeDisabled: 'var(--color-red40)',
  },
  text: {
    onInteractive100: 'var(--color-white100)',
    onInteractiveSecondary60: 'var(--color-white60)',
    onBackground60: 'var(--color-white60)',
    onBackgroundEmphasis100: 'var(--color-white100)',
    disabled: 'var(--color-white20)',
    link: 'var(--color-white100)',
    error: 'var(--color-brand-red)',
    input: 'var(--color-brand-blue)',
    inputPlaceholder: 'var(--color-white-on-blue60)',
    cursor: 'var(--color-brand-dark-blue)',
    success: 'var(--color-brand-green)',
  },
} as const;

export const deprecatedColors = {
  '--color-darker-blue': DeprecatedColorTokens.darkerBlue,
  '--color-dark-blue': DeprecatedColorTokens.darkBlue,
  '--color-blue': DeprecatedColorTokens.blue,
  '--color-dark-green': DeprecatedColorTokens.darkGreen,
  '--color-green': DeprecatedColorTokens.green,
  '--color-red': DeprecatedColorTokens.red,
  '--color-darkYellow': DeprecatedColorTokens.darkYellow,
  '--color-yellow': DeprecatedColorTokens.yellow,
  '--color-black': DeprecatedColorTokens.black,
  '--color-white': DeprecatedColorTokens.white,
  '--color-white-90': DeprecatedColorTokens.white90,
  '--color-white-80': DeprecatedColorTokens.white80,
  '--color-white-60': DeprecatedColorTokens.white60,
  '--color-white-50': DeprecatedColorTokens.white50,
  '--color-white-40': DeprecatedColorTokens.white40,
  '--color-white-20': DeprecatedColorTokens.white20,
  '--color-white-10': DeprecatedColorTokens.white10,
  '--color-blue10': DeprecatedColorTokens.blue10,
  '--color-blue-20': DeprecatedColorTokens.blue20,
  '--color-blue-40': DeprecatedColorTokens.blue40,
  '--color-blue-50': DeprecatedColorTokens.blue50,
  '--color-blue-60': DeprecatedColorTokens.blue60,
  '--color-blue-80': DeprecatedColorTokens.blue80,
  '--color-red-95': DeprecatedColorTokens.red95,
  '--color-red-80': DeprecatedColorTokens.red80,
  '--color-red-60': DeprecatedColorTokens.red60,
  '--color-red-45': DeprecatedColorTokens.red45,
  '--color-red-40': DeprecatedColorTokens.red40,
  '--color-green-90': DeprecatedColorTokens.green90,
  '--color-green-40': DeprecatedColorTokens.green40,
};

export enum DeprecatedColors {
  darkerBlue = 'var(--color-darker-blue)',
  darkBlue = 'var(--color-dark-blue)',
  blue = 'var(--color-blue)',
  darkGreen = 'var(--color-dark-green)',
  green = 'var(--color-green)',
  red = 'var(--color-red)',
  darkYellow = 'var(--color-dark-yellow)',
  yellow = 'var(--color-yellow)',
  black = 'var(--color-black)',
  white = 'var(--color-white)',
  white90 = 'var(--color-white-90)',
  white80 = 'var(--color-white-80)',
  white60 = 'var(--color-white-60)',
  white50 = 'var(--color-white-50)',
  white40 = 'var(--color-white-40)',
  white20 = 'var(--color-white-20)',
  white10 = 'var(--color-white-10)',
  blue10 = 'var(--color-blue-10)',
  blue20 = 'var(--color-blue-20)',
  blue40 = 'var(--color-blue-40)',
  blue50 = 'var(--color-blue-50)',
  blue60 = 'var(--color-blue-60)',
  blue80 = 'var(--color-blue-80)',
  red95 = 'var(--color-red-95)',
  red80 = 'var(--color-red-80)',
  red60 = 'var(--color-red-60)',
  red45 = 'var(--color-red-45)',
  red40 = 'var(--color-red-40)',
  green90 = 'var(--color-green-90)',
  green40 = 'var(--color-green-40)',
}
